openapi: 3.0.0
info:
  title: User Management Service
  version: 1.0.0
  description: API for managing users - fetch, create, update, delete

servers:
  - url: http://localhost:3000/api # Update with your server URL

paths:
  /users:
    get:
      summary: Get users
      description: Retrieve users based on query parameters
      parameters:
        - name: id
          in: query
          description: Filter users by ID
          schema:
            type: string
        - name: phoneNumber
          in: query
          description: Filter users by phone number
          schema:
            type: string
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      summary: Create a user
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    patch:
      summary: Bulk update users
      description: Bulk update users based on query parameters
      parameters:
        - name: id
          in: query
          description: Filter users by ID
          schema:
            type: string
        - name: phoneNumber
          in: query
          description: Filter users by phone number
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Updated users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    delete:
      summary: Bulk delete users
      description: Delete users based on query parameters
      parameters:
        - name: id
          in: query
          description: Filter users by ID
          schema:
            type: string
        - name: phoneNumber
          in: query
          description: Filter users by phone number
          schema:
            type: string
      responses:
        '204':
          description: Users deleted successfully

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
